// Disclaimer:
// This source file was generated by AI (Claude Sonnet 5)

//! A pixel-art-friendly image element for GPUI.
//!
//! `img()` in GPUI always uploads a bitmap at its native resolution and lets
//! the GPU scale/sample it to fit the layout bounds — that GPU-side scaling
//! is what blurs pixel art. `pixel_img()` instead resamples the bitmap with
//! *nearest-neighbor* filtering to the exact on-screen pixel size during
//! `prepaint`, so what reaches the GPU is already 1:1 with the screen and
//! there's nothing left to blur.

use std::collections::HashMap;
use std::sync::{Arc, LazyLock, Mutex};

use gpui::{
    App, Bounds, Element, ElementId, GlobalElementId, Hitbox, Image, InspectorElementId,
    InteractiveElement, Interactivity, IntoElement, LayoutId, Length, ObjectFit, Pixels,
    RenderImage, StyleRefinement, Styled, Window, px,
};
use image::{Frame, ImageBuffer, Rgba, imageops::FilterType};
use smallvec::SmallVec;

/// The source of pixel data for a [`PixelImg`].
///
/// Mirrors gpui's own `ImageSource` — accepts either an already-decoded
/// `RenderImage` or an encoded `Image` asset that will be decoded lazily.
#[derive(Clone)]
pub enum PixelImgSource {
    /// An already-decoded GPU texture.
    Render(Arc<RenderImage>),
    /// An encoded image asset (PNG, JPEG, etc.) that will be decoded via
    /// `use_render_image` on first paint.
    Image(Arc<Image>),
}

impl From<Arc<RenderImage>> for PixelImgSource {
    fn from(v: Arc<RenderImage>) -> Self {
        Self::Render(v)
    }
}

impl From<Arc<Image>> for PixelImgSource {
    fn from(v: Arc<Image>) -> Self {
        Self::Image(v)
    }
}

type CacheKey = (u64, u32, u32);

static RESIZE_CACHE: LazyLock<Mutex<HashMap<CacheKey, Arc<RenderImage>>>> =
    LazyLock::new(|| Mutex::new(HashMap::new()));

fn source_id(source: &PixelImgSource) -> u64 {
    match source {
        PixelImgSource::Image(img) => img.id,
        PixelImgSource::Render(render) => Arc::as_ptr(render) as u64,
    }
}

/// A pixel-art image element: use it like `img()`, but it stays crisp when
/// scaled instead of going blurry.
pub struct PixelImg {
    interactivity: Interactivity,
    source: PixelImgSource,
    object_fit: ObjectFit,
    grayscale: bool,
}

/// Create a pixel-art image element from a render image or encoded image.
///
/// Accepts the same types `img()` does for sources that are already in
/// memory: `Arc<RenderImage>` or `Arc<Image>`.
#[track_caller]
pub fn pixel_img(source: impl Into<PixelImgSource>) -> PixelImg {
    PixelImg {
        interactivity: Interactivity::new(),
        source: source.into(),
        object_fit: ObjectFit::Contain,
        grayscale: false,
    }
}

impl Styled for PixelImg {
    fn style(&mut self) -> &mut StyleRefinement {
        &mut self.interactivity.base_style
    }
}

impl InteractiveElement for PixelImg {
    fn interactivity(&mut self) -> &mut Interactivity {
        &mut self.interactivity
    }
}

/// State handed from `prepaint` to `paint`: the hitbox, plus the
/// already nearest-neighbor-scaled bitmap ready to hand to the GPU.
pub struct PixelImgPrepaintState {
    hitbox: Option<Hitbox>,
    resized: Option<(Bounds<Pixels>, Arc<RenderImage>)>,
}

impl Element for PixelImg {
    type RequestLayoutState = ();
    type PrepaintState = PixelImgPrepaintState;

    fn id(&self) -> Option<ElementId> {
        self.interactivity.element_id.clone()
    }

    fn source_location(&self) -> Option<&'static core::panic::Location<'static>> {
        self.interactivity.source_location()
    }

    fn request_layout(
        &mut self,
        global_id: Option<&GlobalElementId>,
        inspector_id: Option<&InspectorElementId>,
        window: &mut Window,
        cx: &mut App,
    ) -> (LayoutId, Self::RequestLayoutState) {
        let source = self.source.clone();
        let layout_id = self.interactivity.request_layout(
            global_id,
            inspector_id,
            window,
            cx,
            |mut style, window, cx| {
                let data = match &source {
                    PixelImgSource::Image(img) => img.clone().use_render_image(window, cx),
                    PixelImgSource::Render(render) => Some(render.clone()),
                };
                if let Some(data) = data {
                    if data.frame_count() > 0 {
                        let size = data.size(0);
                        let (w, h) = (u32::from(size.width) as f32, u32::from(size.height) as f32);
                        if h > 0.0 {
                            style.aspect_ratio = Some(w / h);
                        }
                        if let Length::Auto = style.size.width {
                            style.size.width = Length::Definite(px(w).into());
                        }
                        if let Length::Auto = style.size.height {
                            style.size.height = Length::Definite(px(h).into());
                        }
                    }
                }
                window.request_layout(style, None, cx)
            },
        );
        (layout_id, ())
    }

    fn prepaint(
        &mut self,
        global_id: Option<&GlobalElementId>,
        inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        window: &mut Window,
        cx: &mut App,
    ) -> Self::PrepaintState {
        let hitbox = self.interactivity.prepaint(
            global_id,
            inspector_id,
            bounds,
            bounds.size,
            window,
            cx,
            |_style, _origin, hitbox, _window, _cx| hitbox,
        );

        let resized = {
            let source = &self.source;
            let data = match source {
                PixelImgSource::Image(img) => img.clone().use_render_image(window, cx),
                PixelImgSource::Render(render) => Some(render.clone()),
            };
            data.and_then(|data| {
                if data.frame_count() == 0 {
                    return None;
                }

                let native = data.size(0);
                let paint_bounds = self.object_fit.get_bounds(bounds, native);

                // Target size in *device* pixels, so it stays crisp on HiDPI too.
                let scale = window.scale_factor();
                let target_w = (u32::from(paint_bounds.size.width) as f32 * scale)
                    .round()
                    .max(1.0) as u32;
                let target_h = (u32::from(paint_bounds.size.height) as f32 * scale)
                    .round()
                    .max(1.0) as u32;

                let id = source_id(source);
                let cache_key = (id, target_w, target_h);

                if let Some(cached) = RESIZE_CACHE.lock().unwrap().get(&cache_key) {
                    return Some((paint_bounds, cached.clone()));
                }

                let bytes = data.as_bytes(0)?;
                let buffer: ImageBuffer<Rgba<u8>, Vec<u8>> = ImageBuffer::from_raw(
                    u32::from(native.width),
                    u32::from(native.height),
                    bytes.to_vec(),
                )?;

                let resized_buffer =
                    image::imageops::resize(&buffer, target_w, target_h, FilterType::Nearest);

                let frame = Frame::new(resized_buffer);
                let render_image = Arc::new(RenderImage::new(SmallVec::<[Frame; 1]>::from_elem(
                    frame, 1,
                )));

                RESIZE_CACHE
                    .lock()
                    .unwrap()
                    .insert(cache_key, render_image.clone());

                Some((paint_bounds, render_image))
            })
        };

        PixelImgPrepaintState { hitbox, resized }
    }

    fn paint(
        &mut self,
        global_id: Option<&GlobalElementId>,
        inspector_id: Option<&InspectorElementId>,
        bounds: Bounds<Pixels>,
        _request_layout: &mut Self::RequestLayoutState,
        prepaint: &mut Self::PrepaintState,
        window: &mut Window,
        cx: &mut App,
    ) {
        let grayscale = self.grayscale;
        let resized = prepaint.resized.take();
        self.interactivity.paint(
            global_id,
            inspector_id,
            bounds,
            prepaint.hitbox.as_ref(),
            window,
            cx,
            |style, window, _cx| {
                if let Some((paint_bounds, data)) = resized {
                    let corner_radii = style
                        .corner_radii
                        .to_pixels(window.rem_size())
                        .clamp_radii_for_quad_size(paint_bounds.size);
                    let _ = window.paint_image(paint_bounds, corner_radii, data, 0, grayscale);
                }
            },
        )
    }
}

impl IntoElement for PixelImg {
    type Element = Self;

    fn into_element(self) -> Self::Element {
        self
    }
}
