name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.platform.name }})
    env:
      ORIG_BIN_NAME: "niko-soundboard"
      NEW_BIN_NAME: "Niko Soundboard"
      FOLDER_NAME: "Niko And Friends"
      ARCHIVE_NAME: "Niko-Soundboard-${{ github.ref_name }}-${{ matrix.platform.name }}.zip"
    strategy:
      matrix:
        platform:
          - name: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe
          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          # - name: macOS-arm64
          #   os: macos-latest
          #   target: aarch64-apple-darwin
          #   ext: ""

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Use cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev libasound2-dev libfontconfig-dev libxcb1-dev libxkbcommon-dev libxkbcommon-x11-dev pkg-config

      - name: Cargo build
        run: cargo build --release --locked --target ${{ matrix.platform.target }}

      - name: Package files
        shell: bash
        run: |
          mkdir -p dist

          mkdir -p "temp/${{ env.FOLDER_NAME }}"
          cp "target/${{ matrix.platform.target }}/release/${{ env.ORIG_BIN_NAME }}${{ matrix.platform.ext }}" \
             "temp/${{ env.FOLDER_NAME }}/${{ env.NEW_BIN_NAME }}${{ matrix.platform.ext }}"
          cp -r characters "temp/${{ env.FOLDER_NAME }}/"
          cd temp
          if [ "$RUNNER_OS" = "Windows" ]; then
            7z a -tzip -mx=9 "../dist/${{ env.ARCHIVE_NAME }}" "${{ env.FOLDER_NAME }}"
          else
            zip -9 -r "../dist/${{ env.ARCHIVE_NAME }}" "${{ env.FOLDER_NAME }}"
          fi
          cd ..
          rm -rf temp

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.platform.name }}
          path: dist/*
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: ./artifacts/**/*
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
